---
abstract: 'JSON RPC 2.0 Server Implementation'
author:
  - 'Daisuke Maki'
build_requires:
  ExtUtils::MakeMaker: '6.36'
  Plack::Request: '0'
  Plack::Test: '0'
  Test::More: '0'
configure_requires:
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs: '0'
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v1.1.0, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JSON-RPC
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  JSON::RPC:
    file: lib/JSON/RPC.pm
    version: '1.06'
  JSON::RPC::Constants:
    file: lib/JSON/RPC/Constants.pm
  JSON::RPC::Dispatch:
    file: lib/JSON/RPC/Dispatch.pm
  JSON::RPC::Legacy:
    file: lib/JSON/RPC/Legacy.pm
  JSON::RPC::Legacy::Client:
    file: lib/JSON/RPC/Legacy/Client.pm
    version: '1.06'
  JSON::RPC::Legacy::Procedure:
    file: lib/JSON/RPC/Legacy/Procedure.pm
    version: '1.06'
  JSON::RPC::Legacy::ReturnObject:
    file: lib/JSON/RPC/Legacy/Client.pm
    version: '0'
  JSON::RPC::Legacy::Server:
    file: lib/JSON/RPC/Legacy/Server.pm
    version: '1.06'
  JSON::RPC::Legacy::Server::Apache:
    file: lib/JSON/RPC/Legacy/Server/Apache2.pm
    version: '1.06'
  JSON::RPC::Legacy::Server::Apache2:
    file: lib/JSON/RPC/Legacy/Server/Apache2.pm
  JSON::RPC::Legacy::Server::CGI:
    file: lib/JSON/RPC/Legacy/Server/CGI.pm
    version: '1.06'
  JSON::RPC::Legacy::Server::Daemon:
    file: lib/JSON/RPC/Legacy/Server/Daemon.pm
    version: '1.06'
  JSON::RPC::Legacy::Server::system:
    file: lib/JSON/RPC/Legacy/Server.pm
  JSON::RPC::Legacy::ServiceObject:
    file: lib/JSON/RPC/Legacy/Client.pm
  JSON::RPC::Parser:
    file: lib/JSON/RPC/Parser.pm
  JSON::RPC::Procedure:
    file: lib/JSON/RPC/Procedure.pm
  JSON::RPC::Test:
    file: lib/JSON/RPC/Test.pm
recommends:
  JSON::XS: '0'
requires:
  CGI: '0'
  Class::Accessor::Lite: '0'
  HTTP::Request: '0'
  HTTP::Response: '0'
  JSON: '0'
  LWP::UserAgent: '0'
  Plack: '0'
  Router::Simple: '0'
  parent: '0'
resources:
  bugtracker: ssh://git@github.com/lestrrat/JSON-RPC/issues
  homepage: ssh://git@github.com/lestrrat/JSON-RPC
  repository: ssh://git@github.com/lestrrat/JSON-RPC.git
version: '1.06'
x_contributors:
  - 'Yoshimitsu Torii <yoshimitsu.torii@gmail.com>'
  - 'Stanislav Lechev [AngelFire] <af@0xAF.org>'
  - 'Kazuhiro Shibuya <stevenlabs@gmail.com>'
  - 'David Steinbrunner <dsteinbrunner@pobox.com>'
  - 'ThePeePs <patrick@thepeeps.net>'
  - 'Kirill Bogdanov <Sco76@hackerdom.ru>'
  - 'ar_tama <makoto.arata@dena.com>'
  - 'Daisuke Maki <lestrrat+github@gmail.com>'
